### ISSUE TITLE
Wrong converting string with numbers

### ISSUE THREAD

**Issue by qwertys318** [miguelmota/to-hex#3]
Wrong converting string with numbers '397755987959' => '5c9c1ab7f7' => '\œ·÷';

**Comment by qwertys318** [comment]
Solved by setting {autoDetectString: false}, but anyway i think this is a trap.

**Comment by miguelmota** [comment]
@qwertys318 Thanks for the issue report. I added additional information to the README. This library was created to solve my use case of converting numbers, whether in number type or string type, to a hex string hence why it's the default option. Maybe the default will be changed in a later version.
